packages:
  - "apps/*"
  - "packages/*"

catalog:
  eslint: "^8"
  typescript: "^5.6.0"
  tailwindcss: "^3.4.12"
  class-variance-authority: "^0.7"
  clsx: "^2.1"
  tailwind-merge: "^2.5"
  "@tailwindcss/typography": "^0.4.0"
  lucide-react: "^0.441"
  postcss-import: "^16.1.0"
  "tailwindcss-animate": "^1.0"
  "react": "19.0.0-rc-5dcb0097-20240918"
  "react-dom": "19.0.0-rc-5dcb0097-20240918"
  "@types/node": "^22.5.4"
  "@types/react": "npm:types-react@19.0.0-rc.1"
  "@types/react-dom": "npm:types-react-dom@19.0.0-rc.1"
  payload: "latest"
  "@payloadcms/db-mongodb": "latest"
  "@payloadcms/next": "latest"
  "@payloadcms/richtext-lexical": "latest"
  "@payloadcms/plugin-cloud": "latest"
  "@payloadcms/eslint-config": "latest"
  "@payloadcms/graphql": "latest"
  "@payloadcms/ui": "latest"
  "@payloadcms/translations": "latest"
  "graphql": "^16.8.1"
  next: "15.0.0-canary.173"
  eslint-config-next: "^15.0.0-rc.0"
  autoprefixer: "^10.4.18"
  postcss: "^8.4.35"
  tsup: "^8.0.2"
  "@testing-library/react": "^16.0.1"
  "@testing-library/jest-dom": "^6.5.0"
  "@testing-library/user-event": "^14.5.2"
  "@testing-library/dom": "^10.4"
  "@vitejs/plugin-react": "^4.3.2"
  "vitest": "^2.1.2"
  "global-jsdom": "^25.0.0"
  
